// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQqHKHcmAC0nJ2v5nijeTNVkhT9sMoF40',
    appId: '1:77161053533:web:dce91a793e966097557cb4',
    messagingSenderId: '77161053533',
    projectId: 'ultimate-metronome-pro',
    authDomain: 'ultimate-metronome-pro.firebaseapp.com',
    storageBucket: 'ultimate-metronome-pro.firebasestorage.app',
    measurementId: 'G-VSVBGY7M38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr6jjSafrd_SITyrnd-Go9FIFytik9lKw',
    appId: '1:77161053533:android:20350b382095c869557cb4',
    messagingSenderId: '77161053533',
    projectId: 'ultimate-metronome-pro',
    storageBucket: 'ultimate-metronome-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpHOQIlbHPcLa5896VCLtZEAqvy2K7Pw',
    appId: '1:77161053533:ios:8364809ef1c64239557cb4',
    messagingSenderId: '77161053533',
    projectId: 'ultimate-metronome-pro',
    storageBucket: 'ultimate-metronome-pro.firebasestorage.app',
    iosBundleId: 'br.com.lenin.canuto.ultimateMetronomePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpHOQIlbHPcLa5896VCLtZEAqvy2K7Pw',
    appId: '1:77161053533:ios:8364809ef1c64239557cb4',
    messagingSenderId: '77161053533',
    projectId: 'ultimate-metronome-pro',
    storageBucket: 'ultimate-metronome-pro.firebasestorage.app',
    iosBundleId: 'br.com.lenin.canuto.ultimateMetronomePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQqHKHcmAC0nJ2v5nijeTNVkhT9sMoF40',
    appId: '1:77161053533:web:2c409f94c9059d5b557cb4',
    messagingSenderId: '77161053533',
    projectId: 'ultimate-metronome-pro',
    authDomain: 'ultimate-metronome-pro.firebaseapp.com',
    storageBucket: 'ultimate-metronome-pro.firebasestorage.app',
    measurementId: 'G-W8EFQRGTQM',
  );
}
